added an example workflow to the documentation
fossology/fossology-python pull request #74
Opened 2021-08-09 14:43 UTC by thsetz

2021-08-11 14:02 UTC, deveaud-m requested changes
Thanks for this contribution.

I made some comments and suggestions.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  if not os.path.isfile(".token"):
```suggestion
  if not os.path.exists(".token"):
```

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +    print("username/password within the testenvironment is fossy/fossy")
```suggestion
    print("Enter your Fossology credentials, e.g. in the test environment 'username: fossy' and 'password: fossy'")
```

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +    token = fp.read()
The file doesn't need to be re-opened if the token has just been generated, indentation of those three lines could be shifted to the right.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +Login to the fossology Server
```suggestion
Login to the Fossology Server
```

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert test_folder.description == folder_desc
This snippet has been copied from the test, assertions are irrelevant in this context.

As far as I remember, the method `create_folder` also returns the folder object if it already exists.

This sample code could be shortened to the three lines 90...93.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert test_group.name == group_name
Same remark als before.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  if not os.path.isfile(os.path.join("/tmp", filename)):
Please use [`Pathlib`](https://docs.python.org/3/library/pathlib.html) here.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert os.path.isfile(os.path.join("/tmp", filename))
Please use [`Pathlib`](https://docs.python.org/3/library/pathlib.html) here.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert my_upload.uploadname == test_file
Remove assertions from the sample code.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +    # XXX create_group does not return created group
```suggestion
    # The name of the group created by `create_group` can be used in subsequent call to restrict access to resources from this group, see https://fossology.github.io/fossology-python/groups.html for further resources
```

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +
Small introduction about the jobs spec could be written here, see Fossology documentation regarding the different agents, deciders and reuse options.

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +Write report to disk
The three steps should be merges together in one "section".

2021-08-11 14:02 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +Output
This section can be deleted.

2021-08-11 17:30 UTC, thsetz commented on docs-source/sample_workflow.rst
> +    token = fp.read()
OK

2021-08-11 17:30 UTC, thsetz commented on docs-source/sample_workflow.rst
> +Login to the fossology Server
OK

2021-08-11 17:35 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  assert test_folder.description == folder_desc
OK

2021-08-11 17:46 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  assert test_group.name == group_name
If the group already exists, create_group throws an exception:

- fossology.exceptions.FossologyApiError: ('Group clearing already exists, failed to create group or no group name provided', <Response [500]>)

That is, why i check it again - and use the assert .

2021-08-11 20:37 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  if not os.path.isfile(".token"):
For consistency  I used pathlib instead.

2021-08-11 20:40 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  if not os.path.isfile(os.path.join("/tmp", filename)):
OK

2021-08-11 20:40 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  assert os.path.isfile(os.path.join("/tmp", filename))
OK

2021-08-11 20:40 UTC, thsetz commented on docs-source/sample_workflow.rst
> +  assert my_upload.uploadname == test_file
OK

2021-08-11 20:42 UTC, thsetz commented on docs-source/sample_workflow.rst
> +    # XXX create_group does not return created group
OK

2021-08-11 20:42 UTC, thsetz commented on docs-source/sample_workflow.rst
> +
OK

2021-08-11 20:42 UTC, thsetz commented on docs-source/sample_workflow.rst
> +Write report to disk
OK

2021-08-11 20:42 UTC, thsetz commented on docs-source/sample_workflow.rst
> +Output
OK

2021-08-12 06:05 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +    token = fp.read()
@thsetz you can resolve the discussions once you pushed the requested changes as a new commit.

2021-08-12 06:06 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +Login to the fossology Server
@thsetz if you commit the suggestion the discussion will be resolved automatically

2021-08-12 06:12 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert test_group.name == group_name
We should catch the exception in this example to show users of the API how to handle the different cases: group is created or group already exists.

2021-08-12 06:21 UTC, deveaud-m commented
Thanks for addressing all the discussions. Only one comment regarding group creation handling is left.

2021-08-12 23:13 UTC, thsetz commented
Maybe it's a good idea to rewrite sample_workflow.rst with doctest. I just tried it - but that. collides with some doctests in the library - which would need to be fixed too.

2021-08-13 07:13 UTC, deveaud-m commented on docs-source/sample_workflow.rst
> +  assert test_group.name == group_name
Discussion has been addressed.

2021-08-13 07:37 UTC, deveaud-m approved these changes
All changes look good. Ready to be merged.

2021-08-13 07:37 UTC, merged